const languages = {
    "en": {
    "write-to-us": "Write to us",
    "top-bar-address": "44, J.Jabbarli Street, Caspian Plaza 1, 4th Floor Baku, Azerbaijan",
    "top-bar-schedule": "Mon-Sat 09:00-21:00",
    "nav-home": "Home Page",
    "nav-gallery": "Gallery",
    "nav-abroad": "Studying Abroad",
    "nav-store": "Book Store",
    "nav-courses": "Courses",
    "nav-tests": "Tests",
    "nav-info": "Information",
    "nav-more": "More",
    "swiper-learn": "Learn languages and connect with the world",
    "swiper-apply1": "Apply",
    "swiper-global": "Become a global citizen with multi-language",
    "swiper-apply2": "Apply",
    "advantages": "Our advantages",
    "advantages-effective": "100% Effective",
    "advantages-translators": "You will be taught by the best translators in English language courses",
    "advantages-course": "Intensive course",
    "advantages-opportunity": "Opportunity to study according to the accelerated method of Kifayat Ahmad gizi without homework",
    "advantages-textbooks": "Textbooks",
    "advantages-range": "There is a wide range of additional materials and resources for our students",
    "popular-courses": "Our Popular Courses",
    "courses-en": "English Courses Hekimler Ucun",
    "courses-az": "Azerbaijani Courses",
    "courses-ru": "Russian Courses",
    "courses-de": "German Courses",
    "courses-sp": "Spanish Courses",
    "courses-fr": "French Courses",
    "courses-more1": "More",
    "courses-more2": "More",
    "courses-more3": "More",
    "courses-more4": "More",
    "courses-more5": "More",
    "courses-more6": "More",
    "courses-more7": "More",
    "apply-info": "Get free information",
    "apply-send": "SEND",
    "start-speaking": "START SPEAKING FOREIGN LANGUAGE IN 48 HOURS",
    "why": "WHY CHOOSE US?",
    "info-description": "\"The Language House\" is a training center where studies are conducted by professional teachers, as well as native speakers. In our school you can appreciate a variety of services, which include various training programs considered for children and adults, for groups or one person at any level of proficiency – zero and medium.",
    "stats-books": "Our books",
    "stats-courses": "Programs & Courses",
    "stats-experience": "Years of Experience",
    "latest-news": "Latest News",
    "news-title": "Kifayat Ahmadgizi",
    "news-description": "Kifayat Ahmad Gizi Our web site has been updated. Lorem Ipsum &nbsp; is simply dummy text of the printing and typesetting industry...",
    "book-store": "Book Store",
    "start-now-start": "Start now and turn your knowledge into a profitable online course",
    "start-now-get-started": "Get started now",
    "footer-address": "44, J.Jabbarli Street, Caspian Plaza 1, 4th Floor Baku, Azerbaijan",
    "footer-popular-courses": "Popular Courses",
    "footer-en-courses": "English Courses",
    "footer-az-courses": "Azerbaijani Courses",
    "footer-ru-courses": "Russian Courses",
    "footer-de-courses": "German Courses",
    "footer-sp-courses": "Spanish Courses",
    "footer-news": "News",
    "footer-about": "About Us",
    "footer-study": "Studies",
    "footer-contact": "Contact",
    "footer-book-store": "Book Store",
    "footer-contact": "Contact us",
    "all-rr": "Copyright 2024 Kifayat Ahmadgizi. All Rights Reserved.",
    "dev": "This site is developed by "
},
"ru": {
    "write-to-us": "Напишите нам",
    "top-bar-address": "44, ул. Дж. Джаббарлы, Каспий Плаза 1, 4-й этаж, Баку, Азербайджан",
    "top-bar-schedule": "Пн-Сб 09:00-21:00",
    "nav-home": "Главная страница",
    "nav-gallery": "Галерея",
    "nav-abroad": "Обучение за границей",
    "nav-store": "Книжный магазин",
    "nav-courses": "Курсы",
    "nav-tests": "Тесты",
    "nav-info": "Информация",
    "nav-more": "Ещё",
    "swiper-learn": "Изучайте языки и соединяйтесь с миром",
    "swiper-apply1": "Записаться",
    "swiper-global": "Станьте гражданином мира с многоязычием",
    "swiper-apply2": "Записаться",
    "advantages": "Наши преимущества",
    "advantages-effective": "100% Эффективно",
    "advantages-translators": "Вас будут обучать лучшие переводчики на курсах английского языка",
    "advantages-course": "Интенсивный курс",
    "advantages-opportunity": "Возможность учиться по ускоренной методике Кифайят Ахмад гызы без домашних заданий",
    "advantages-textbooks": "Учебники",
    "advantages-range": "Широкий ассортимент дополнительных материалов и ресурсов для наших студентов",
    "popular-courses": "Наши популярные курсы",
    "courses-en": "Курсы английского языка для врачей",
    "courses-az": "Курсы азербайджанского языка",
    "courses-ru": "Курсы русского языка",
    "courses-de": "Курсы немецкого языка",
    "courses-sp": "Курсы испанского языка",
    "courses-fr": "Курсы французского языка",
    "courses-more1": "Ещё",
    "courses-more2": "Ещё",
    "courses-more3": "Ещё",
    "courses-more4": "Ещё",
    "courses-more5": "Ещё",
    "courses-more6": "Ещё",
    "courses-more7": "Ещё",
    "apply-info": "Получите бесплатную информацию",
    "apply-send": "ОТПРАВИТЬ",
    "start-speaking": "НАЧНИТЕ ГОВОРИТЬ НА ИНОСТРАННОМ ЯЗЫКЕ ЗА 48 ЧАСОВ",
    "why": "ПОЧЕМУ ВЫБИРАЮТ НАС?",
    "info-description": "\"The Language House\" — это учебный центр, где занятия проводят профессиональные преподаватели и носители языка. В нашей школе вы сможете оценить разнообразие услуг, включая различные учебные программы, рассчитанные на детей и взрослых, для групп или индивидуальных занятий на любом уровне владения языком — от нуля до среднего.",
    "stats-books": "Наши книги",
    "stats-courses": "Программы и курсы",
    "stats-experience": "Годы опыта",
    "latest-news": "Последние новости",
    "news-title": "Кифайят Ахмадгизи",
    "news-description": "Наш сайт был обновлен. Lorem Ipsum &nbsp; - это просто текст-заполнитель в полиграфической и издательской индустрии...",
    "book-store": "Книжный магазин",
    "start-now-start": "Начните сейчас и превратите свои знания в прибыльный онлайн-курс",
    "start-now-get-started": "Начать сейчас",
    "footer-address": "44, ул. Дж. Джаббарлы, Каспий Плаза 1, 4-й этаж, Баку, Азербайджан",
    "footer-popular-courses": "Популярные курсы",
    "footer-en-courses": "Курсы английского языка",
    "footer-az-courses": "Курсы азербайджанского языка",
    "footer-ru-courses": "Курсы русского языка",
    "footer-de-courses": "Курсы немецкого языка",
    "footer-sp-courses": "Курсы испанского языка",
    "footer-news": "Новости",
    "footer-about": "О нас",
    "footer-study": "Обучение",
    "footer-contact": "Контакты",
    "footer-book-store": "Книжный магазин",
    "footer-contact": "Связаться с нами",
    "all-rr": "Авторские права 2024 Кифайят Ахмадгизи. Все права защищены.",
    "dev": "Этот сайт разработан "
},
"az": {
    "write-to-us": "Bizə yazın",
    "top-bar-address": "44, C.Cabbarlı küç., Xəzər Plaza 1, 4-cü mərtəbə, Bakı, Azərbaycan",
    "top-bar-schedule": "B.e.-Şənbə 09:00-21:00",
    "nav-home": "Ana Səhifə",
    "nav-gallery": "Qalereya",
    "nav-abroad": "Xaricdə Təhsil",
    "nav-store": "Kitab Mağazası",
    "nav-courses": "Kurslar",
    "nav-tests": "Testlər",
    "nav-info": "Məlumat",
    "nav-more": "Daha çox",
    "swiper-learn": "Dilləri öyrənin və dünya ilə əlaqə qurun",
    "swiper-apply1": "Müraciət et",
    "swiper-global": "Çoxdilli vətəndaş olun",
    "swiper-apply2": "Müraciət et",
    "advantages": "Üstünlüklərimiz",
    "advantages-effective": "100% Effektiv",
    "advantages-translators": "Sizi ingilis dili kurslarında ən yaxşı tərcüməçilər öyrədəcək",
    "advantages-course": "Intensiv kurs",
    "advantages-opportunity": "Ev tapşırığı olmadan Kifayət Əhməd qızı sürətli təlim metodu ilə oxumaq imkanı",
    "advantages-textbooks": "Dərsliklər",
    "advantages-range": "Tələbələrimiz üçün çoxlu əlavə materiallar və resurslar mövcuddur",
    "popular-courses": "Populyar Kurslarımız",
    "courses-en": "Həkimlər üçün İngilis Dili Kursları",
    "courses-az": "Azərbaycan Dili Kursları",
    "courses-ru": "Rus Dili Kursları",
    "courses-de": "Alman Dili Kursları",
    "courses-sp": "İspan Dili Kursları",
    "courses-fr": "Fransız Dili Kursları",
    "courses-more1": "Daha çox",
    "courses-more2": "Daha çox",
    "courses-more3": "Daha çox",
    "courses-more4": "Daha çox",
    "courses-more5": "Daha çox",
    "courses-more6": "Daha çox",
    "courses-more7": "Daha çox",
    "apply-info": "Pulsuz məlumat əldə edin",
    "apply-send": "GÖNDƏR",
    "start-speaking": "48 SAAT İÇƏRİSİNDƏ XARİCİ DİLDƏ DANIŞMAĞA BAŞLAYIN",
    "why": "NİYƏ BİZİ SEÇMƏLİSİNİZ?",
    "info-description": "\"The Language House\" peşəkar müəllimlər və doğma dillər tərəfindən tədris olunan bir təlim mərkəzidir. Məktəbimizdə uşaqlar və böyüklər üçün, qruplar və ya fərdi şəxslər üçün müxtəlif təhsil proqramlarını qiymətləndirə bilərsiniz – sıfır və orta səviyyələrdə.",
    "stats-books": "Kitablarımız",
    "stats-courses": "Proqramlar və Kurslar",
    "stats-experience": "İllik Təcrübə",
    "latest-news": "Ən son Xəbərlər",
    "news-title": "Kifayət Əhməd qızı",
    "news-description": "Veb saytımız yeniləndi. Lorem Ipsum sadəcə çap və tərtibat sənayesindəki yalan mətn...",
    "book-store": "Kitab Mağazası",
    "start-now-start": "İndi başlayın və biliklərinizi mənfəətli onlayn kursa çevirin",
    "start-now-get-started": "İndi başlayın",
    "footer-address": "44, C.Cabbarlı küç., Xəzər Plaza 1, 4-cü mərtəbə, Bakı, Azərbaycan",
    "footer-popular-courses": "Populyar Kurslar",
    "footer-en-courses": "İngilis Dili Kursları",
    "footer-az-courses": "Azərbaycan Dili Kursları",
    "footer-ru-courses": "Rus Dili Kursları",
    "footer-de-courses": "Alman Dili Kursları",
    "footer-sp-courses": "İspan Dili Kursları",
    "footer-news": "Xəbərlər",
    "footer-about": "Haqqımızda",
    "footer-study": "Tədris",
    "footer-contact": "Əlaqə",
    "footer-book-store": "Kitab Mağazası",
    "footer-contact": "Bizimlə əlaqə",
    "all-rr": "Müəllif hüquqları 2024 Kifayət Əhməd qızı. Bütün hüquqlar qorunur.",
    "dev": "Bu sayt tərəfindən hazırlanmışdır "
}
}